### ISSUE TITLE
macOS compilation

### ISSUE THREAD

**Issue by grylem** [kiyolee/libmd-port#1]
Hi
please add makefile for macOS,  i tried makefile.unx but too many errors.
Thanks.

**Comment by kiyolee** [comment]
Unfortunately I have no access to any mac.
Can you show me the errors and let me check if that is something obvious?
Btw, what does the command "uname -m" output on macOS?

**Comment by grylem** [comment]
of course
uname -m
x86_64

add #include <stdint.h> to crypto/sha2/
make -f Makefile.unx
errors (without warnings):
as --defsym SKEIN_USE_ASM=1792  --noexecstack -o skein_block_asm.o crypto/skein/amd64/skein_block_asm.s
clang: error: unsupported option '--defsym'
clang: error: unsupported option '--noexecstack'
clang: error: no such file or directory: 'SKEIN_USE_ASM=1792'

**Comment by kiyolee** [comment]
The assembler is too old. Or is it actually GNU as? Would like to know what "as --version" shows.
Perhaps the simplest solution is to disable assembly, try the following gmake command:
gmake -f Makefile.unx NO_X64_ASM=yes
I will fix the requirement of <stdint.h> that is kind of make sense.

**Comment by grylem** [comment]
make -f Makefile.unx NO_X64_ASM=yes
too many warnings end one error
ld: unknown option: -shared
macOS use -dynamic instead -shared
Manually
ar rcs libmd.a  *.o
go to md5
make -f Makefile.unx
errors:
md5.c:319:19: error: use of undeclared identifier 'optarg'
md5.c:332:33: error: use of undeclared identifier 'optarg'
md5.c:343:10: error: use of undeclared identifier 'optind'
etc.
go to libmd
ld -dynamic md4c.o md5c.o md4hl.o md5hl.o rmd160c.o rmd160hl.o sha0c.o sha0hl.o sha1c.o sha1hl.o sha224hl.o sha256c.o sha256hl.o sha512c.o sha512hl.o sha512t224hl.o sha512t256hl.o sha384hl.o skein.o skein_block.o skein256hl.o skein512hl.o skein1024hl.o -o libmd.so

Undefined symbols for architecture x86_64:
"___bzero", referenced from:
"___error"
etc, etc

**Comment by grylem** [comment]
in md5.c change #ifdef unix to #ifdef __APPLE__ and now md5 compiled with libmd.a

**Comment by kiyolee** [comment]
Added Makefile.osx for MacOSX.
May need further refinement though, especially about dylib support.
